{"uuid": "c32bf41c-c0b3-4080-8278-9996b3e5e6de", "children": ["b4cb5b36-39cd-474f-849b-0a5d80b0c274", "eb92e9c2-5bd9-45fd-a6e4-79106cb40346", "0aa7b594-6afa-4308-944c-84f246c587fc", "9f212782-7c31-476f-8e96-297c2898031a"], "befores": [{"name": "login_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of MSEdgeDriver only supports MSEdge version 85\n\n", "trace": "  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\工具资料\\GitHub\\python_web_autotest\\testcase\\conftest.py\", line 21, in login_setup_class\n    driver = Edge(executable_path=config.get(\"ENV\", \"drive_path\"))\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\edge\\webdriver.py\", line 66, in __init__\n    desired_capabilities=capabilities)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1607737469747, "stop": 1607737471315}], "start": 1607737469747, "stop": 1607737472476}