{"uuid": "fde3b2ab-0fc4-423c-bc56-5c68a30ad581", "children": ["213b1e24-9e38-411b-a7ec-06761839ef9f", "071f5168-1586-491f-b5a5-4cfe6c5b1e4c", "4e83c2a2-d52e-491d-b06d-fefa6384ef12", "466bc426-fb8c-48d9-a145-4ded974e697e"], "befores": [{"name": "login_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of MSEdgeDriver only supports MSEdge version 85\n\n", "trace": "  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\工具资料\\GitHub\\python_web_autotest\\testcase\\conftest.py\", line 21, in login_setup_class\n    driver = Edge(executable_path=config.get(\"ENV\", \"drive_path\"))\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\edge\\webdriver.py\", line 66, in __init__\n    desired_capabilities=capabilities)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\64121\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1607777604745, "stop": 1607777606436}], "start": 1607777604745, "stop": 1607777607550}